import { expect, test } from '@playwright/test'

test('file context menu exposes actions in list and grid views', async ({ page }) => {
  const folder = `e2e-context-${Date.now()}`

  await page.goto('/login')
  await page.getByLabel('用户名').fill('demo')
  await page.getByLabel('密码').fill('OmniStore-Test-Demo!')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByRole('button', { name: '打开存储源 团队文件' }).click()
  await page.getByRole('button', { name: '创建文件夹' }).click()
  const createDialog = page.getByRole('dialog', { name: '新建文件夹' })
  await createDialog.getByLabel('目录名').fill(folder)
  await createDialog.getByRole('button', { name: '创建', exact: true }).click()

  const row = page.getByRole('row', { name: new RegExp(folder) })
  await row.click({ button: 'right' })
  let menu = page.getByRole('menu')
  await expect(menu).toBeVisible()
  await page.screenshot({ path: '/tmp/omni-store-file-context-menu.png' })
  await expect(menu.getByRole('menuitem', { name: '打开' })).toBeVisible()
  await expect(menu.getByRole('menuitem', { name: '剪切' })).toBeVisible()
  await expect(menu.getByRole('menuitem', { name: '移入回收站' })).toBeVisible()
  await menu.getByRole('menuitem', { name: '复制', exact: true }).click()
  await expect(page.getByRole('region', { name: '文件剪贴板' })).toContainText('已复制 1 项')

  await page.getByRole('tab', { name: '网格视图' }).click()
  await page.getByText(folder, { exact: true }).click({ button: 'right' })
  menu = page.getByRole('menu')
  await expect(menu).toBeVisible()
  await expect(menu.getByRole('menuitem', { name: '重命名' })).toBeVisible()
  await menu.getByRole('menuitem', { name: '打开' }).click()
  await expect(page.getByRole('navigation', { name: '面包屑' })).toContainText(folder)
  await page.getByRole('navigation', { name: '面包屑' }).getByText('团队文件', { exact: true }).click()
  await page.getByRole('tab', { name: '列表视图' }).click()
  const createdRow = page.getByRole('row', { name: new RegExp(folder) })
  await createdRow.getByRole('button', { name: `更多操作 ${folder}` }).click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await page.getByRole('dialog', { name: '移入回收站' }).getByRole('button', { name: '移入回收站' }).click()
  const trashResponse = page.waitForResponse((response) => response.request().method() === 'GET' && response.url().includes('/trash'))
  await page.getByRole('button', { name: '回收站' }).click()
  await trashResponse
  const trashedRow = page.locator('tbody tr').filter({ hasText: folder })
  await trashedRow.getByRole('button', { name: '永久删除' }).click()
  const purgeResponse = page.waitForResponse((response) => response.request().method() === 'DELETE' && response.url().includes('/trash/'))
  await page.getByRole('dialog', { name: '永久删除' }).getByRole('button', { name: '永久删除', exact: true }).click()
  expect((await purgeResponse).ok()).toBeTruthy()
  await expect(trashedRow).toHaveCount(0)
})
