import { globalStyle, style } from '@vanilla-extract/css'
import { vars } from '../styles/theme.css'

export const hero = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.lg, marginBottom: vars.space.lg, padding: `${vars.space.lg} 0`, borderBottom: `1px solid ${vars.color.border}`, '@media': { 'screen and (max-width: 640px)': { alignItems: 'flex-start', flexDirection: 'column' } } })
export const identity = style({ display: 'flex', alignItems: 'center', gap: vars.space.md, minWidth: 0 })
export const icon = style({ width: 54, height: 54, flex: '0 0 auto', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: vars.color.primary, background: vars.color.primarySubtle, borderRadius: vars.radius.tile })
export const title = style({ overflow: 'hidden', margin: 0, color: vars.color.text, fontSize: vars.fontSize.xxl, textOverflow: 'ellipsis', whiteSpace: 'nowrap' })
export const meta = style({ display: 'flex', flexWrap: 'wrap', gap: '6px 14px', marginTop: 7, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })
export const actions = style({ display: 'flex', flexShrink: 0, gap: vars.space.sm })
export const linkButton = style({ height: 38, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 7, padding: '0 14px', color: vars.color.textOnPrimary, background: vars.color.primary, borderRadius: vars.radius.md, fontSize: vars.fontSize.sm, fontWeight: 600, textDecoration: 'none', selectors: { '&:hover': { background: vars.color.primaryHover }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 2 } } })
export const unlockWrap = style({ minHeight: 480, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: vars.space.lg })
export const unlockCard = style({ width: '100%', maxWidth: 420, padding: vars.space.lg, background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg, boxShadow: vars.shadow.md, textAlign: 'center' })
export const unlockIcon = style({ width: 58, height: 58, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginBottom: vars.space.md, color: vars.color.primary, background: vars.color.primarySubtle, borderRadius: vars.radius.tile })
globalStyle(`${unlockCard} h1`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.xxl })
globalStyle(`${unlockCard} p`, { margin: '8px 0 20px', color: vars.color.textSecondary, lineHeight: 1.6 })
export const unlockForm = style({ display: 'grid', gap: vars.space.sm })
export const error = style({ color: vars.color.danger, fontSize: vars.fontSize.sm, textAlign: 'left' })
export const empty = style({ minHeight: 420, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: vars.space.sm, color: vars.color.textSecondary, textAlign: 'center' })
globalStyle(`${empty} h1`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.xxl })
globalStyle(`${empty} p`, { margin: 0, lineHeight: 1.6 })
export const crumbs = style({ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 6, marginBottom: vars.space.md, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })
export const crumbButton = style({ padding: 0, color: vars.color.textSecondary, background: 'none', border: 0, cursor: 'pointer', font: 'inherit', selectors: { '&:hover': { color: vars.color.primary } } })
export const currentCrumb = style({ color: vars.color.text, fontWeight: 600 })
export const pager = style({ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: vars.space.sm, marginTop: vars.space.md, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })

// —— Share 2.0（1.2.0） ——
export const toolbar = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: vars.space.sm, marginBottom: vars.space.md })
export const toolbarActions = style({ display: 'flex', alignItems: 'center', gap: vars.space.sm, flexWrap: 'wrap' })
export const zipButton = style({ height: 34, display: 'inline-flex', alignItems: 'center', gap: 6, padding: '0 12px', color: vars.color.text, background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.md, fontSize: vars.fontSize.sm, fontWeight: 600, textDecoration: 'none', selectors: { '&:hover': { borderColor: vars.color.borderStrong, background: vars.color.surfaceHover }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 2 } } })
export const viewToggle = style({ display: 'inline-flex', gap: 2, background: vars.color.surfaceHover, borderRadius: vars.radius.full, padding: 2 })
export const viewOption = style({ display: 'inline-flex', alignItems: 'center', gap: 5, padding: '5px 12px', border: 0, borderRadius: vars.radius.full, background: 'transparent', color: vars.color.textSecondary, font: 'inherit', fontSize: vars.fontSize.sm, cursor: 'pointer', selectors: { '&:hover': { color: vars.color.text }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 2 }, '&:disabled': { opacity: 0.4, cursor: 'not-allowed' } } })
export const viewOptionActive = style({ background: vars.color.surface, color: vars.color.text, boxShadow: vars.shadow.sm, cursor: 'default' })
export const gallery = style({ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: vars.space.sm, marginBottom: vars.space.md })
export const galleryCell = style({ position: 'relative' })
export const galleryItem = style({ display: 'block', width: '100%', aspectRatio: '1 / 1', padding: 0, border: 0, background: vars.color.surfaceHover, borderRadius: vars.radius.md, overflow: 'hidden', cursor: 'zoom-in', boxShadow: vars.shadow.sm, selectors: { '&:hover': { boxShadow: vars.shadow.md }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 2 } } })
export const galleryImg = style({ width: '100%', height: '100%', objectFit: 'cover', display: 'block' })
export const galleryName = style({ position: 'absolute', left: 4, right: 4, bottom: 4, padding: '14px 6px 2px', fontSize: vars.fontSize.xs, color: '#fff', textAlign: 'center', background: 'linear-gradient(transparent, oklch(0.2 0.03 258 / 0.72))', borderRadius: vars.radius.sm, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', pointerEvents: 'none' })
export const galleryCount = style({ display: 'block', marginTop: vars.space.sm, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })
// 文件分享内嵌预览容器：媒体/PDF 需要稳定高度，文本族内部滚动。
export const embedPreview = style({ height: 'min(72vh, 760px)', marginBottom: vars.space.xl, display: 'flex', flexDirection: 'column' })
