import { globalStyle, style } from '@vanilla-extract/css'
import { vars } from '../styles/theme.css'

export const header = style({ marginBottom: 24 })
export const eyebrow = style({ display: 'block', marginBottom: 8, color: vars.color.primary, fontSize: vars.fontSize.xs, fontWeight: 700, letterSpacing: '0.1em' })
export const title = style({ margin: 0, color: vars.color.text, fontSize: vars.fontSize.display, lineHeight: 1.1, letterSpacing: '-0.045em' })
export const description = style({ margin: '10px 0 0', color: vars.color.textSecondary, lineHeight: 1.6 })
export const panel = style({ overflow: 'hidden', background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg, boxShadow: vars.shadow.sm })
export const panelHeader = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.md, padding: '15px 18px', borderBottom: `1px solid ${vars.color.border}`, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })
globalStyle(`${panelHeader} h2`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.sm, fontWeight: 650 })
export const list = style({ display: 'grid' })
export const row = style({ display: 'grid', gridTemplateColumns: '42px minmax(0, 1fr) auto 36px', alignItems: 'center', gap: vars.space.md, padding: '13px 18px', borderBottom: `1px solid ${vars.color.border}`, selectors: { '&:last-child': { borderBottom: 0 }, '&:hover': { background: vars.color.surfaceHover } }, '@media': { 'screen and (max-width: 640px)': { gridTemplateColumns: '36px minmax(0, 1fr) 44px', gap: vars.space.sm, padding: '12px' } } })
export const fileIcon = style({ width: 38, height: 38, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: vars.color.primary, background: vars.color.primarySubtle, borderRadius: vars.radius.md })
export const identity = style({ display: 'grid', gap: 5, minWidth: 0 })
export const fileName = style({ width: 'fit-content', maxWidth: '100%', overflow: 'hidden', padding: 0, border: 0, background: 'transparent', color: vars.color.text, font: 'inherit', fontWeight: 650, textAlign: 'left', textOverflow: 'ellipsis', whiteSpace: 'nowrap', cursor: 'pointer', selectors: { '&:hover': { color: vars.color.primary }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 2 } } })
export const location = style({ display: 'flex', alignItems: 'center', gap: 4, minWidth: 0, overflow: 'hidden', padding: 0, border: 0, background: 'transparent', color: vars.color.textSecondary, fontSize: vars.fontSize.xs, textAlign: 'left', textOverflow: 'ellipsis', whiteSpace: 'nowrap', cursor: 'pointer', selectors: { '&:hover': { color: vars.color.primary }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 2 } } })
globalStyle(`${location} svg`, { flexShrink: 0 })
export const metadata = style({ display: 'grid', justifyItems: 'end', gap: 4, color: vars.color.textSecondary, fontSize: vars.fontSize.xs, whiteSpace: 'nowrap', '@media': { 'screen and (max-width: 640px)': { display: 'none' } } })
export const download = style({ width: 34, height: 34, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: vars.color.textSecondary, borderRadius: vars.radius.sm, textDecoration: 'none', selectors: { '&:hover': { color: vars.color.primary, background: vars.color.primarySubtle }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 1 } }, '@media': { 'screen and (max-width: 640px)': { width: 44, height: 44 } } })
export const state = style({ minHeight: 270, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: vars.space.sm, padding: vars.space.xl, color: vars.color.textSecondary, textAlign: 'center', background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg })
globalStyle(`${state} h2`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.lg })
globalStyle(`${state} p`, { maxWidth: 480, margin: 0, lineHeight: 1.6 })
globalStyle(`${state} a`, { color: vars.color.primary, fontWeight: 600, textDecoration: 'none' })
export const emptyIcon = style({ width: 54, height: 54, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginBottom: 4, color: vars.color.primary, background: vars.color.primarySubtle, borderRadius: vars.radius.tile })
