import { globalStyle, style } from '@vanilla-extract/css'
import { vars } from '../styles/theme.css'

export const header = style({ marginBottom: 24 })
export const eyebrow = style({ display: 'block', marginBottom: 8, color: vars.color.primary, fontSize: vars.fontSize.xs, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase' })
export const title = style({ margin: 0, color: vars.color.text, fontSize: vars.fontSize.display, lineHeight: 1.1, letterSpacing: '-0.045em' })
export const description = style({ margin: '10px 0 0', color: vars.color.textSecondary, lineHeight: 1.6 })
export const searchPanel = style({ display: 'grid', gridTemplateColumns: 'minmax(260px, 1fr) 220px auto', alignItems: 'center', gap: vars.space.sm, marginBottom: 20, padding: vars.space.md, background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg, boxShadow: vars.shadow.sm, '@media': { 'screen and (max-width: 760px)': { gridTemplateColumns: '1fr' } } })
export const queryField = style({ height: 42, display: 'flex', alignItems: 'center', gap: 10, padding: '0 13px', color: vars.color.textSecondary, background: vars.color.background, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.md, selectors: { '&:focus-within': { borderColor: vars.color.primary, boxShadow: `0 0 0 3px ${vars.color.primarySubtle}` } } })
globalStyle(`${queryField} input`, { width: '100%', minWidth: 0, border: 0, outline: 0, color: vars.color.text, background: 'transparent', font: 'inherit' })
globalStyle(`${queryField} input::placeholder`, { color: vars.color.textSecondary })
export const srOnly = style({ position: 'absolute', width: 1, height: 1, padding: 0, margin: -1, overflow: 'hidden', clip: 'rect(0, 0, 0, 0)', whiteSpace: 'nowrap', border: 0 })
export const emptyState = style({ minHeight: 300, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: vars.space.sm, padding: vars.space.xl, color: vars.color.textSecondary, textAlign: 'center', background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg })
globalStyle(`${emptyState} h2`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.lg })
globalStyle(`${emptyState} p`, { maxWidth: 500, margin: 0, lineHeight: 1.6 })
export const emptyIcon = style({ width: 58, height: 58, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginBottom: 4, color: vars.color.primary, background: vars.color.primarySubtle, borderRadius: vars.radius.tile })
export const results = style({ overflow: 'hidden', background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg, boxShadow: vars.shadow.sm })
export const resultsHeader = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '15px 18px', color: vars.color.textSecondary, borderBottom: `1px solid ${vars.color.border}`, fontSize: vars.fontSize.sm })
globalStyle(`${resultsHeader} > div`, { display: 'flex', alignItems: 'baseline', gap: 6 })
globalStyle(`${resultsHeader} h2`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.sm, fontWeight: 600 })
export const resultCount = style({ color: vars.color.primary, fontSize: vars.fontSize.xl, fontWeight: 750 })
export const resultList = style({ display: 'grid' })
export const resultRow = style({ display: 'grid', gridTemplateColumns: '40px minmax(0, 1fr) auto auto', alignItems: 'center', gap: vars.space.md, padding: '14px 18px', borderBottom: `1px solid ${vars.color.border}`, selectors: { '&:last-child': { borderBottom: 0 }, '&:hover': { background: vars.color.surfaceHover } }, '@media': { 'screen and (max-width: 680px)': { gridTemplateColumns: '36px minmax(0, 1fr) auto', gap: vars.space.sm } } })
export const fileIcon = style({ width: 38, height: 38, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: vars.color.primary, background: vars.color.primarySubtle, borderRadius: vars.radius.md })
export const fileIdentity = style({ minWidth: 0 })
globalStyle(`${fileIdentity} a`, { display: 'block', overflow: 'hidden', color: vars.color.text, fontWeight: 650, textDecoration: 'none', textOverflow: 'ellipsis', whiteSpace: 'nowrap' })
globalStyle(`${fileIdentity} a:hover`, { color: vars.color.primary })
globalStyle(`${fileIdentity} span`, { display: 'block', overflow: 'hidden', marginTop: 4, color: vars.color.textSecondary, fontFamily: vars.font.mono, fontSize: vars.fontSize.xs, textOverflow: 'ellipsis', whiteSpace: 'nowrap' })
export const fileMeta = style({ display: 'grid', justifyItems: 'end', gap: 3, color: vars.color.textSecondary, fontSize: vars.fontSize.xs, whiteSpace: 'nowrap', '@media': { 'screen and (max-width: 680px)': { display: 'none' } } })
export const actions = style({ display: 'flex', gap: 4 })
globalStyle(`${actions} button, ${actions} a`, { width: 32, height: 32, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', padding: 0, color: vars.color.textSecondary, background: 'transparent', border: 0, borderRadius: vars.radius.sm, cursor: 'pointer', textDecoration: 'none' })
globalStyle(`${actions} button:hover, ${actions} a:hover`, { color: vars.color.primary, background: vars.color.primarySubtle })
globalStyle(`${actions} button:focus-visible, ${actions} a:focus-visible`, { outline: `2px solid ${vars.color.primary}`, outlineOffset: 1 })
export const pagination = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.md, padding: '14px 18px', color: vars.color.textSecondary, borderTop: `1px solid ${vars.color.border}`, fontSize: vars.fontSize.sm, '@media': { 'screen and (max-width: 520px)': { gap: vars.space.xs } } })
