import { style } from '@vanilla-extract/css'
import { vars } from '../styles/theme.css'

export const pageHeader = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: vars.space.lg })
export const pageTitle = style({ margin: 0, fontSize: vars.fontSize.xxl, color: vars.color.text })
export const panel = style({ display: 'grid', gap: vars.space.sm })
export const emptyState = style({ display: 'grid', justifyContent: 'center', justifyItems: 'center', gap: vars.space.xs, padding: `${vars.space.xl} ${vars.space.lg}`, color: vars.color.textSecondary, textAlign: 'center' })
export const emptyIcon = style({ color: vars.color.primary, opacity: 0.7 })
export const row = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.md, padding: vars.space.md, background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg, '@media': { 'screen and (max-width: 720px)': { alignItems: 'flex-start', flexDirection: 'column' } } })
export const rowMain = style({ minWidth: 0 })
export const rowTitle = style({ margin: 0, color: vars.color.text, fontSize: vars.fontSize.lg, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' })
export const rowMeta = style({ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '6px 14px', marginTop: 6, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })
export const rowActions = style({ display: 'flex', flexShrink: 0, flexWrap: 'wrap', gap: vars.space.xs })
export const pickupOnce = style({ display: 'grid', gap: vars.space.md })
export const pickupCodeRow = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.sm, padding: vars.space.sm, background: vars.color.surfaceHover, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.md })
export const pickupCode = style({ fontFamily: vars.font.mono, fontSize: vars.fontSize.xl, letterSpacing: 4, color: vars.color.text })
export const pickupLink = style({ fontFamily: vars.font.mono, fontSize: vars.fontSize.sm, wordBreak: 'break-all', color: vars.color.text })
export const pickupHint = style({ margin: 0, color: vars.color.textSecondary, fontSize: vars.fontSize.sm, lineHeight: 1.6 })
export const draftActions = style({ display: 'flex', flexWrap: 'wrap', gap: vars.space.xs, marginBottom: vars.space.md })
export const hiddenInput = style({ display: 'none' })
export const draftFiles = style({ listStyle: 'none', margin: `0 0 ${vars.space.md}`, padding: 0, display: 'grid', gap: 4, maxHeight: 260, overflowY: 'auto' })
export const draftFileRow = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.sm, padding: '6px 10px', background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.sm })
export const draftFilePath = style({ fontFamily: vars.font.mono, fontSize: vars.fontSize.sm, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: vars.color.text })
export const draftFileSize = style({ flexShrink: 0, color: vars.color.textSecondary, fontSize: vars.fontSize.sm })
export const breadcrumb = style({ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: vars.space.sm, fontSize: vars.fontSize.sm })
export const browserList = style({ display: 'grid', gap: 4, maxHeight: 300, overflowY: 'auto', border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.md, padding: vars.space.sm })
export const browserEmpty = style({ color: vars.color.textSecondary, fontSize: vars.fontSize.sm, padding: vars.space.md, textAlign: 'center' })
export const browserRow = style({ display: 'flex', alignItems: 'center', gap: vars.space.sm, padding: '4px 6px', borderRadius: vars.radius.sm, fontSize: vars.fontSize.sm, color: vars.color.text })
export const browserDirButton = style({ border: 'none', background: 'none', padding: 0, cursor: 'pointer', color: vars.color.primary, fontWeight: 600, fontSize: vars.fontSize.sm })
export const browserName = style({ color: vars.color.text })
