import { globalStyle, style } from '@vanilla-extract/css'
import { vars } from '../styles/theme.css'

export const header = style({ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: vars.space.lg, marginBottom: 28, '@media': { 'screen and (max-width: 620px)': { alignItems: 'flex-start', flexDirection: 'column' } } })
export const back = style({ display: 'inline-flex', alignItems: 'center', gap: 4, border: 0, padding: '4px 0', marginBottom: 14, background: 'transparent', color: vars.color.textSecondary, fontSize: vars.fontSize.sm, cursor: 'pointer', selectors: { '&:hover': { color: vars.color.primary }, '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 3 } } })
export const title = style({ margin: 0, color: vars.color.text, fontSize: vars.fontSize.display, lineHeight: 1.1, letterSpacing: '-0.045em' })
export const description = style({ margin: '10px 0 0', color: vars.color.textSecondary, lineHeight: 1.6 })
export const panel = style({ overflow: 'hidden', minHeight: 260, background: vars.color.surface, border: `1px solid ${vars.color.border}`, borderRadius: vars.radius.lg, boxShadow: vars.shadow.sm })
export const tableWrap = style({ overflowX: 'auto' })
export const table = style({ width: '100%', minWidth: 760, borderCollapse: 'collapse', color: vars.color.text, fontSize: vars.fontSize.sm, '@media': { 'screen and (max-width: 980px)': { minWidth: 0 } } })
globalStyle(`${table} th`, { padding: '12px 16px', borderBottom: `1px solid ${vars.color.border}`, color: vars.color.textSecondary, fontWeight: 600, textAlign: 'left', whiteSpace: 'nowrap' })
globalStyle(`${table} td`, { padding: '13px 16px', borderBottom: `1px solid ${vars.color.border}`, verticalAlign: 'middle' })
globalStyle(`${table} tbody tr:last-child td`, { borderBottom: 0 })
globalStyle(`${table} tbody tr:hover`, { backgroundColor: vars.color.surfaceHover })
export const nameCell = style({ display: 'inline-flex', alignItems: 'center', gap: 9, minWidth: 0, fontWeight: 600 })
globalStyle(`${nameCell} svg`, { flexShrink: 0, color: vars.color.primary })
export const pathCell = style({ maxWidth: 300, overflow: 'hidden', color: vars.color.textSecondary, fontFamily: vars.font.mono, textOverflow: 'ellipsis', whiteSpace: 'nowrap', '@media': { 'screen and (max-width: 980px)': { display: 'none' } } })
export const timeCell = style({ whiteSpace: 'nowrap', '@media': { 'screen and (max-width: 720px)': { display: 'none' } } })
export const sizeCell = style({ whiteSpace: 'nowrap', '@media': { 'screen and (max-width: 520px)': { display: 'none' } } })
export const actions = style({ display: 'flex', justifyContent: 'flex-end', gap: 4 })
const actionBase = style({ width: 32, height: 32, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', border: 0, borderRadius: vars.radius.sm, background: 'transparent', cursor: 'pointer', selectors: { '&:focus-visible': { outline: `2px solid ${vars.color.primary}`, outlineOffset: 1 } } })
export const action = style([actionBase, { color: vars.color.primary, selectors: { '&:hover': { backgroundColor: vars.color.primarySubtle } } }])
export const dangerAction = style([actionBase, { color: vars.color.danger, selectors: { '&:hover': { backgroundColor: vars.color.dangerSubtle } } }])
export const centerState = style({ minHeight: 240, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: vars.space.md, padding: vars.space.xl, color: vars.color.textSecondary, textAlign: 'center' })
export const empty = style([centerState])
globalStyle(`${empty} h2`, { margin: 0, color: vars.color.text, fontSize: vars.fontSize.lg })
globalStyle(`${empty} p`, { margin: 0 })
export const emptyIcon = style({ width: 54, height: 54, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', borderRadius: vars.radius.tile, background: vars.color.surfaceHover, color: vars.color.textSecondary })
const notice = style({ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: vars.space.md, marginBottom: vars.space.md, padding: '11px 14px', borderRadius: vars.radius.md, fontSize: vars.fontSize.sm })
globalStyle(`${notice} button`, { border: 0, background: 'transparent', color: 'inherit', fontWeight: 600, cursor: 'pointer' })
export const noticeSuccess = style([notice, { color: vars.color.success, backgroundColor: vars.color.successSubtle }])
export const noticeError = style([notice, { color: vars.color.danger, backgroundColor: vars.color.dangerSubtle }])
export const dialogText = style({ margin: 0, color: vars.color.textSecondary, lineHeight: 1.6 })
export const dialogError = style({ margin: 0, color: vars.color.danger, lineHeight: 1.6 })
